### ISSUE TITLE
What about removing some of logging calls?

### ISSUE THREAD

**Issue by tarik02** [pmmp/PreProcessor#9]
What about using very aggressive optimization with removing logger calls? We can detect these lines of code with searching these fragments:
- `getLogger()->debug`
- `logger->debug`

This can be very helpful especially for people who never enables debugging in production servers.

**Comment by dktapps** [comment]
Next you'll want to optimize away timings.

I have considered this previously, but I think it's unwise because it removes the ability to enable debug mode at all. The performance gains you get by doing this are microscopic, so it doesn't really make sense.
